spring:
  application:
    name: spring-study-todo
  config:
    additional-location: .env

  datasource:
    url: jdbc:postgresql://localhost:5432/auth-springboot-demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8075

jwt:
  secret: dvgjbhkj551dzafrevc2663q2ds1d4e522sf5ss52dfd54df5qdffff
